"""
Game Data Loader — loads and caches game constants from JSON files.

Engines import from here when they want authoritative data from the JSON
files rather than their inline constants.  The JSON files are the canonical
reference for future patch updates.

Data sources:
  /data/affixes.json          — generated by scripts/sync_game_data.py from last-epoch-data
  /data/skills_metadata.json  — generated by scripts/sync_game_data.py from last-epoch-data
  /data/enemy_profiles.json   — hand-curated enemy profiles for simulation
  /backend/app/game_data/classes.json — curated class/mastery/attribute data
  /backend/app/game_data/skills.json  — curated engine-specific skill stats

Usage:
    from app.game_data.game_data_loader import (
        get_class_base_stats,
        get_mastery_bonuses,
        get_keystone_bonuses,
        get_attribute_scaling,
        get_affix_tier_midpoints,
        get_affix_stat_keys,
        get_all_affixes,
        get_affixes_by_category,
        get_affixes_by_slot,
        get_affixes_by_tag,
        get_affix_by_id,
        get_skill_stats,
        get_skill_metadata,
        get_all_skills_metadata,
    )
"""

import json
import math
import os
from functools import lru_cache

_DATA_DIR = os.path.dirname(__file__)

# Canonical data files live in /data/ at the project root
_ROOT_DIR = os.path.abspath(os.path.join(_DATA_DIR, "..", "..", ".."))
_AFFIXES_PATH = os.path.join(_ROOT_DIR, "data", "affixes.json")
_ENEMY_PROFILES_PATH = os.path.join(_ROOT_DIR, "data", "enemy_profiles.json")
_SKILLS_METADATA_PATH = os.path.join(_ROOT_DIR, "data", "skills_metadata.json")


def _load(filename: str) -> dict:
    path = os.path.join(_DATA_DIR, filename)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def _classes() -> dict:
    return _load("classes.json")


@lru_cache(maxsize=1)
def _affixes_raw() -> list:
    """Load the canonical flat affix list from /data/affixes.json."""
    with open(_AFFIXES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def _skills() -> dict:
    return _load("skills.json")


# ------------------------------------------------------------------
# Derived affix lookups — built once from the v2.0 affixes.json
# ------------------------------------------------------------------

@lru_cache(maxsize=1)
def _build_affix_lookups() -> tuple[dict, dict]:
    """Build tier-midpoints and stat-keys dicts from the canonical affix list."""
    affix_list = _affixes_raw()

    midpoints: dict[str, dict[str, float]] = {}
    stat_keys: dict[str, str] = {}

    for affix in affix_list:
        name = affix["name"]
        # stat_key may not exist in the new schema — fall back to id
        stat_keys[name] = affix.get("stat_key", affix["id"])
        mp: dict[str, float] = {}
        for tier_entry in affix.get("tiers", []):
            lo, hi = tier_entry["min"], tier_entry["max"]
            mp[f"T{tier_entry['tier']}"] = math.floor((lo + hi) / 2)
        midpoints[name] = mp

    return midpoints, stat_keys


def get_affix_tier_midpoints() -> dict:
    """Returns affix name → {T1: mid, T2: mid, …} mapping (all categories)."""
    return _build_affix_lookups()[0]


def get_affix_stat_keys() -> dict:
    """Returns affix display name → BuildStats field name mapping."""
    return _build_affix_lookups()[1]


def get_all_affixes() -> list[dict]:
    """Returns the full flat list of affix definitions from the canonical JSON."""
    return _affixes_raw()


def get_affixes_by_category(category: str) -> list[dict]:
    """Returns affix definitions filtered by type (prefix/suffix)."""
    return [a for a in get_all_affixes() if a.get("type") == category]


def get_affix_categories() -> dict:
    """Returns a summary of affix type counts."""
    from collections import Counter
    counts = Counter(a["type"] for a in get_all_affixes())
    return dict(counts)


# ------------------------------------------------------------------
# Class / skill data
# ------------------------------------------------------------------

def get_class_base_stats() -> dict:
    """Returns base stats dict keyed by class name."""
    return _classes()["base_stats"]


def get_mastery_bonuses() -> dict:
    """Returns flat mastery bonus dicts keyed by mastery name."""
    return _classes()["mastery_bonuses"]


def get_mastery_per_point() -> dict:
    """Returns per-passive-point bonuses for masteries that scale with points used."""
    return _classes()["mastery_per_point"]


def get_keystone_bonuses() -> dict:
    """Returns keystone passive bonus dicts keyed by keystone name."""
    return _classes()["keystone_bonuses"]


def get_attribute_scaling() -> dict:
    """Returns attribute → BuildStats field scaling ratios."""
    return _classes()["attribute_scaling"]


def get_skill_stats() -> dict:
    """Returns skill name → stat definition dict."""
    return _skills()["skills"]


@lru_cache(maxsize=1)
def _enemy_profiles_raw() -> list:
    with open(_ENEMY_PROFILES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def get_enemy_profiles() -> list[dict]:
    """Returns all enemy profile definitions."""
    return _enemy_profiles_raw()


def get_enemy_profile(enemy_id: str) -> dict | None:
    """Returns a single enemy profile by id, or None if not found."""
    for profile in _enemy_profiles_raw():
        if profile.get("id") == enemy_id:
            return profile
    return None


# ------------------------------------------------------------------
# Enriched data from last-epoch-data sync
# ------------------------------------------------------------------

@lru_cache(maxsize=1)
def _skills_metadata_raw() -> dict:
    """Load skills metadata (name, description, lore) generated by sync_game_data.py."""
    if not os.path.exists(_SKILLS_METADATA_PATH):
        return {}
    with open(_SKILLS_METADATA_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def get_skill_metadata(skill_name: str) -> dict | None:
    """Returns metadata dict for a skill (description, lore, class) or None."""
    return _skills_metadata_raw().get(skill_name)


def get_all_skills_metadata() -> dict:
    """Returns the full skill name → metadata dict."""
    return _skills_metadata_raw()


def get_affixes_by_slot(slot: str) -> list[dict]:
    """Returns all equipment affixes that can roll on the given slot slug (e.g. 'helm')."""
    return [a for a in get_all_affixes() if slot in a.get("applicable_to", [])]


def get_affixes_by_tag(tag: str) -> list[dict]:
    """Returns all affixes that carry the given tag (e.g. 'fire', 'minion')."""
    tag = tag.lower()
    return [a for a in get_all_affixes() if tag in [t.lower() for t in a.get("tags", [])]]


def get_affix_by_id(affix_id: int) -> dict | None:
    """Returns a single affix by its numeric game id, or None."""
    for affix in get_all_affixes():
        if affix.get("affix_id") == affix_id:
            return affix
    return None
