"""Deterministic runtime transition foundation models.

The runtime transition package models non-executable orchestration-planning
coordination transition evidence. It does not execute, route, schedule,
dispatch, traverse, mutate, optimize, recommend, rank, score, select,
authorize, or create callable orchestration behavior.
"""

from .transition_foundation_continuity import (
    CONTINUITY_TYPE_EVIDENCE,
    CONTINUITY_TYPE_EXPLAINABILITY,
    CONTINUITY_TYPE_PROVENANCE,
    CONTINUITY_TYPE_REPLAY,
    CONTINUITY_TYPE_ROLLBACK,
    TransitionContinuityChain,
    TransitionContinuityReference,
    export_transition_continuity_chain,
    export_transition_continuity_reference,
    transition_continuity_chain_key,
    transition_continuity_reference_key,
)
from .transition_foundation_hashing import (
    deterministic_hash,
    hash_v3_9_transition_continuity_reference,
    hash_v3_9_transition_foundation,
    hash_v3_9_transition_identity,
    hash_v3_9_transition_provenance_reference,
    hash_v3_9_transition_reference,
    hash_v3_9_transition_state_reference,
)
from .transition_foundation_models import (
    TRANSITION_CLASSIFICATION_BLOCKED,
    TRANSITION_CLASSIFICATION_INCOMPLETE,
    TRANSITION_CLASSIFICATION_PROHIBITED,
    TRANSITION_CLASSIFICATION_SUPPORTED,
    TRANSITION_CLASSIFICATION_UNKNOWN,
    TRANSITION_CLASSIFICATION_UNSUPPORTED,
    TRANSITION_CLASSIFICATIONS,
    TRANSITION_VISIBILITY_FAIL_VISIBLE,
    TRANSITION_VISIBILITY_VISIBLE,
    TransitionEvidenceRecord,
    TransitionFoundation,
    TransitionIdentity,
    TransitionReference,
    TransitionStateReference,
    V3_9_TRANSITION_FOUNDATION_PHASE_ID,
    V3_9_TRANSITION_FOUNDATION_STATUS_BLOCKED,
    V3_9_TRANSITION_FOUNDATION_STATUS_STABLE,
    V3_9_TRANSITION_SCHEMA_VERSION,
    build_transition_identity,
    default_v3_9_transition_foundation,
    export_transition_evidence_record,
    export_transition_identity,
    export_transition_reference,
    export_transition_state_reference,
    export_v3_9_transition_foundation,
    identity_values_are_unique,
    transition_identity_key,
    transition_reference_key,
    transition_state_reference_key,
)
from .transition_foundation_provenance import (
    TransitionProvenanceReference,
    export_transition_provenance_reference,
    transition_provenance_key,
)
from .transition_foundation_serialization import (
    serialize_v3_9_transition_foundation,
    stable_serialize,
)
from .transition_foundation_validation import (
    count_v3_9_transition_classifications,
    validate_v3_9_transition_foundation_guarantees,
    validate_v3_9_transition_hash_stability,
    validate_v3_9_transition_serialization_stability,
)
from .transition_boundary_classifier import (
    classify_v3_9_transition_boundaries,
    default_transition_boundary_inputs,
)
from .transition_boundary_models import (
    BOUNDARY_CLASSIFICATION_BLOCKED,
    BOUNDARY_CLASSIFICATION_INCOMPLETE,
    BOUNDARY_CLASSIFICATION_PROHIBITED,
    BOUNDARY_CLASSIFICATION_SAFE,
    BOUNDARY_CLASSIFICATION_UNKNOWN,
    BOUNDARY_CLASSIFICATION_UNSUPPORTED,
    BOUNDARY_CLASSIFICATIONS,
    TransitionBoundaryClassification,
    TransitionBoundaryEvidence,
    TransitionBoundaryFinding,
    TransitionBoundaryInput,
    TransitionBoundaryReport,
    export_transition_boundary_report,
    transition_boundary_finding_id,
)
from .transition_boundary_report import (
    build_v3_9_transition_boundary_intelligence_report,
)
from .transition_boundary_serialization import (
    hash_transition_boundary_report,
    serialize_transition_boundary_report,
    validate_transition_boundary_hash_stability,
    validate_transition_boundary_serialization_stability,
)
from .transition_boundary_validation import (
    count_transition_boundary_classifications,
    validate_transition_boundary_report,
)

__all__ = [
    "CONTINUITY_TYPE_EVIDENCE",
    "CONTINUITY_TYPE_EXPLAINABILITY",
    "CONTINUITY_TYPE_PROVENANCE",
    "CONTINUITY_TYPE_REPLAY",
    "CONTINUITY_TYPE_ROLLBACK",
    "TransitionContinuityChain",
    "TransitionContinuityReference",
    "export_transition_continuity_chain",
    "export_transition_continuity_reference",
    "transition_continuity_chain_key",
    "transition_continuity_reference_key",
    "deterministic_hash",
    "hash_v3_9_transition_continuity_reference",
    "hash_v3_9_transition_foundation",
    "hash_v3_9_transition_identity",
    "hash_v3_9_transition_provenance_reference",
    "hash_v3_9_transition_reference",
    "hash_v3_9_transition_state_reference",
    "TRANSITION_CLASSIFICATION_BLOCKED",
    "TRANSITION_CLASSIFICATION_INCOMPLETE",
    "TRANSITION_CLASSIFICATION_PROHIBITED",
    "TRANSITION_CLASSIFICATION_SUPPORTED",
    "TRANSITION_CLASSIFICATION_UNKNOWN",
    "TRANSITION_CLASSIFICATION_UNSUPPORTED",
    "TRANSITION_CLASSIFICATIONS",
    "TRANSITION_VISIBILITY_FAIL_VISIBLE",
    "TRANSITION_VISIBILITY_VISIBLE",
    "TransitionEvidenceRecord",
    "TransitionFoundation",
    "TransitionIdentity",
    "TransitionReference",
    "TransitionStateReference",
    "V3_9_TRANSITION_FOUNDATION_PHASE_ID",
    "V3_9_TRANSITION_FOUNDATION_STATUS_BLOCKED",
    "V3_9_TRANSITION_FOUNDATION_STATUS_STABLE",
    "V3_9_TRANSITION_SCHEMA_VERSION",
    "build_transition_identity",
    "default_v3_9_transition_foundation",
    "export_transition_evidence_record",
    "export_transition_identity",
    "export_transition_reference",
    "export_transition_state_reference",
    "export_v3_9_transition_foundation",
    "identity_values_are_unique",
    "transition_identity_key",
    "transition_reference_key",
    "transition_state_reference_key",
    "TransitionProvenanceReference",
    "export_transition_provenance_reference",
    "transition_provenance_key",
    "serialize_v3_9_transition_foundation",
    "stable_serialize",
    "count_v3_9_transition_classifications",
    "validate_v3_9_transition_foundation_guarantees",
    "validate_v3_9_transition_hash_stability",
    "validate_v3_9_transition_serialization_stability",
    "classify_v3_9_transition_boundaries",
    "default_transition_boundary_inputs",
    "BOUNDARY_CLASSIFICATION_BLOCKED",
    "BOUNDARY_CLASSIFICATION_INCOMPLETE",
    "BOUNDARY_CLASSIFICATION_PROHIBITED",
    "BOUNDARY_CLASSIFICATION_SAFE",
    "BOUNDARY_CLASSIFICATION_UNKNOWN",
    "BOUNDARY_CLASSIFICATION_UNSUPPORTED",
    "BOUNDARY_CLASSIFICATIONS",
    "TransitionBoundaryClassification",
    "TransitionBoundaryEvidence",
    "TransitionBoundaryFinding",
    "TransitionBoundaryInput",
    "TransitionBoundaryReport",
    "export_transition_boundary_report",
    "transition_boundary_finding_id",
    "build_v3_9_transition_boundary_intelligence_report",
    "hash_transition_boundary_report",
    "serialize_transition_boundary_report",
    "validate_transition_boundary_hash_stability",
    "validate_transition_boundary_serialization_stability",
    "count_transition_boundary_classifications",
    "validate_transition_boundary_report",
]
