"""Report builders for deterministic v3.9 transition integrity enforcement."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .transition_foundation_hashing import deterministic_hash
from .transition_integrity_audit import audit_v3_9_transition_integrity
from .transition_integrity_models import (
    INTEGRITY_CLASSIFICATION_BLOCKED,
    INTEGRITY_CLASSIFICATION_FAILED,
    INTEGRITY_CLASSIFICATION_INCOMPLETE,
    INTEGRITY_CLASSIFICATION_PROHIBITED,
    INTEGRITY_CLASSIFICATION_SATISFIED,
    INTEGRITY_CLASSIFICATION_UNKNOWN,
    INTEGRITY_CLASSIFICATION_UNSUPPORTED,
    INTEGRITY_CLASSIFICATION_WARNING,
    INTEGRITY_VIOLATION_AGGREGATION_INTEGRITY_GAP,
    INTEGRITY_VIOLATION_EXECUTION_BOUNDARY_LEAK,
    INTEGRITY_VIOLATION_EXPLAINABILITY_GAP,
    INTEGRITY_VIOLATION_HIDDEN_FINDING,
    INTEGRITY_VIOLATION_HIDDEN_NON_SAFE_STATE,
    INTEGRITY_VIOLATION_HIDDEN_RISK,
    INTEGRITY_VIOLATION_MISSING_AGGREGATION_EVIDENCE,
    INTEGRITY_VIOLATION_MISSING_BOUNDARY_EVIDENCE,
    INTEGRITY_VIOLATION_MISSING_COMPATIBILITY_EVIDENCE,
    INTEGRITY_VIOLATION_MISSING_EVALUATION_EVIDENCE,
    INTEGRITY_VIOLATION_MISSING_EVIDENCE_GAP,
    INTEGRITY_VIOLATION_MISSING_FOUNDATION_EVIDENCE,
    INTEGRITY_VIOLATION_MISSING_SCENARIO_EVIDENCE,
    INTEGRITY_VIOLATION_MISSING_SESSION_EVIDENCE,
    INTEGRITY_VIOLATION_MUTATION_LEAK,
    INTEGRITY_VIOLATION_PROHIBITED_VISIBILITY_GAP,
    INTEGRITY_VIOLATION_PROVENANCE_GAP,
    INTEGRITY_VIOLATION_RANKING_LEAK,
    INTEGRITY_VIOLATION_RECOMMENDATION_LEAK,
    INTEGRITY_VIOLATION_REPLAY_GAP,
    INTEGRITY_VIOLATION_ROLLBACK_GAP,
    INTEGRITY_VIOLATION_SCORING_LEAK,
    INTEGRITY_VIOLATION_SELECTION_LEAK,
    INTEGRITY_VIOLATION_UNKNOWN_VISIBILITY_GAP,
    INTEGRITY_VIOLATION_UNSUPPORTED_VISIBILITY_GAP,
    export_transition_integrity_report,
)
from .transition_integrity_serialization import (
    hash_transition_integrity_report,
    validate_transition_integrity_hash_stability,
    validate_transition_integrity_serialization_stability,
)
from .transition_integrity_validation import validate_transition_integrity_report


DETERMINISTIC_GENERATED_AT = "2026-05-17T00:00:00+00:00"

SOURCE_ARTIFACT_PATHS: tuple[str, ...] = (
    "docs/generated/v3_9_transition_foundations_report.json",
    "docs/migration/V3_9_TRANSITION_FOUNDATIONS.md",
    "docs/generated/v3_9_transition_boundary_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_BOUNDARY_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_compatibility_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_COMPATIBILITY_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_evaluation_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_EVALUATION_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_session_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_SESSION_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_scenario_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_SCENARIO_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_intelligence_aggregation_report.json",
    "docs/migration/V3_9_TRANSITION_INTELLIGENCE_AGGREGATION.md",
)


def build_v3_9_transition_integrity_enforcement_report(repo_root: Path | None = None) -> dict[str, Any]:
    root = repo_root or Path(__file__).resolve().parents[3]
    integrity_report = audit_v3_9_transition_integrity()
    validation = validate_transition_integrity_report(integrity_report)
    serialization = validate_transition_integrity_serialization_stability(integrity_report)
    hashing = validate_transition_integrity_hash_stability(integrity_report)
    source_artifacts = [_source_artifact_status(root, path) for path in SOURCE_ARTIFACT_PATHS]
    source_artifact_count = len(source_artifacts)
    present_source_artifact_count = sum(1 for artifact in source_artifacts if artifact["present"])
    report = {
        "schema_version": "v3_9.transition_integrity_enforcement_report.1",
        "generated_at": DETERMINISTIC_GENERATED_AT,
        "phase_name": "v3.9_transition_integrity_enforcement",
        "repo_root": str(root),
        "architectural_purpose": "deterministic audit-only transition integrity enforcement without remediation",
        "integrity_report_status": integrity_report.report_status,
        "source_aggregation_report_id": integrity_report.source_aggregation_report_id,
        "source_aggregation_hash": integrity_report.source_aggregation_hash,
        "non_executable": integrity_report.non_executable,
        "orchestration_execution_enabled": integrity_report.orchestration_execution_enabled,
        "transition_execution_enabled": integrity_report.transition_execution_enabled,
        "graph_traversal_enabled": integrity_report.graph_traversal_enabled,
        "routing_enabled": integrity_report.routing_enabled,
        "scheduling_enabled": integrity_report.scheduling_enabled,
        "dispatch_enabled": integrity_report.dispatch_enabled,
        "runtime_orchestration_engine_enabled": integrity_report.runtime_orchestration_engine_enabled,
        "runtime_mutation_enabled": integrity_report.runtime_mutation_enabled,
        "authorization_enabled": integrity_report.authorization_enabled,
        "approval_enabled": integrity_report.approval_enabled,
        "optimization_enabled": integrity_report.optimization_enabled,
        "recommendation_enabled": integrity_report.recommendation_enabled,
        "ranking_enabled": integrity_report.ranking_enabled,
        "scoring_enabled": integrity_report.scoring_enabled,
        "selection_enabled": integrity_report.selection_enabled,
        "remediation_enabled": integrity_report.remediation_enabled,
        "repair_enabled": integrity_report.repair_enabled,
        "automatic_remediation_enabled": integrity_report.automatic_remediation_enabled,
        "automatic_repair_enabled": integrity_report.automatic_repair_enabled,
        "hidden_fallback_enabled": integrity_report.hidden_fallback_enabled,
        "silent_correction_enabled": integrity_report.silent_correction_enabled,
        "prioritization_enabled": integrity_report.prioritization_enabled,
        "weighted_severity_scoring_enabled": integrity_report.weighted_severity_scoring_enabled,
        "source_artifacts": source_artifacts,
        "source_artifact_totals": {
            "source_artifact_count": source_artifact_count,
            "present_source_artifact_count": present_source_artifact_count,
            "missing_source_artifact_count": source_artifact_count - present_source_artifact_count,
            "source_artifact_continuity_preserved": present_source_artifact_count == source_artifact_count,
        },
        "integrity_classification_counts": dict(integrity_report.summary.classification_counts),
        "integrity_finding_counts": dict(integrity_report.summary.finding_category_counts),
        "integrity_violation_counts": dict(integrity_report.summary.violation_type_counts),
        "integrity_visibility_counts": dict(integrity_report.summary.visibility_category_counts),
        "integrity_totals": {
            "integrity_input_count": validation["integrity_input_count"],
            "integrity_satisfied_count": validation["integrity_satisfied_count"],
            "integrity_warning_count": validation["integrity_warning_count"],
            "integrity_failed_count": validation["integrity_failed_count"],
            "blocked_count": validation["blocked_count"],
            "unsupported_count": validation["unsupported_count"],
            "prohibited_count": validation["prohibited_count"],
            "unknown_count": validation["unknown_count"],
            "incomplete_count": validation["incomplete_count"],
            "integrity_finding_count": validation["integrity_finding_count"],
            "integrity_violation_count": validation["integrity_violation_count"],
            "hidden_finding_violation_count": validation["hidden_finding_violation_count"],
            "hidden_risk_violation_count": validation["hidden_risk_violation_count"],
            "hidden_non_safe_state_violation_count": validation[
                "hidden_non_safe_state_violation_count"
            ],
            "missing_evidence_violation_count": validation["missing_evidence_violation_count"],
            "provenance_gap_count": validation["provenance_gap_count"],
            "replay_gap_count": validation["replay_gap_count"],
            "rollback_gap_count": validation["rollback_gap_count"],
            "explainability_gap_count": validation["explainability_gap_count"],
            "aggregation_integrity_gap_count": validation["aggregation_integrity_gap_count"],
            "execution_boundary_leakage_count": validation["execution_boundary_leakage_count"],
            "recommendation_leakage_count": validation["recommendation_leakage_count"],
            "ranking_leakage_count": validation["ranking_leakage_count"],
            "scoring_leakage_count": validation["scoring_leakage_count"],
            "selection_leakage_count": validation["selection_leakage_count"],
            "mutation_leakage_count": validation["mutation_leakage_count"],
            "visibility_gap_count": validation["visibility_gap_count"],
        },
        "violation_semantics": {
            INTEGRITY_VIOLATION_HIDDEN_FINDING: "hidden finding detection",
            INTEGRITY_VIOLATION_HIDDEN_RISK: "hidden risk detection",
            INTEGRITY_VIOLATION_HIDDEN_NON_SAFE_STATE: "hidden non-safe state detection",
            INTEGRITY_VIOLATION_MISSING_FOUNDATION_EVIDENCE: "missing foundation evidence",
            INTEGRITY_VIOLATION_MISSING_BOUNDARY_EVIDENCE: "missing boundary evidence",
            INTEGRITY_VIOLATION_MISSING_COMPATIBILITY_EVIDENCE: "missing compatibility evidence",
            INTEGRITY_VIOLATION_MISSING_EVALUATION_EVIDENCE: "missing evaluation evidence",
            INTEGRITY_VIOLATION_MISSING_SESSION_EVIDENCE: "missing session evidence",
            INTEGRITY_VIOLATION_MISSING_SCENARIO_EVIDENCE: "missing scenario evidence",
            INTEGRITY_VIOLATION_MISSING_AGGREGATION_EVIDENCE: "missing aggregation evidence",
            INTEGRITY_VIOLATION_PROVENANCE_GAP: "provenance continuity gap",
            INTEGRITY_VIOLATION_REPLAY_GAP: "replay continuity gap",
            INTEGRITY_VIOLATION_ROLLBACK_GAP: "rollback continuity gap",
            INTEGRITY_VIOLATION_EXPLAINABILITY_GAP: "explainability continuity gap",
            INTEGRITY_VIOLATION_AGGREGATION_INTEGRITY_GAP: "aggregation integrity gap",
            INTEGRITY_VIOLATION_EXECUTION_BOUNDARY_LEAK: "execution-boundary leakage",
            INTEGRITY_VIOLATION_RECOMMENDATION_LEAK: "recommendation leakage",
            INTEGRITY_VIOLATION_RANKING_LEAK: "ranking leakage",
            INTEGRITY_VIOLATION_SCORING_LEAK: "scoring leakage",
            INTEGRITY_VIOLATION_SELECTION_LEAK: "selection leakage",
            INTEGRITY_VIOLATION_MUTATION_LEAK: "mutation leakage",
            INTEGRITY_VIOLATION_UNSUPPORTED_VISIBILITY_GAP: "unsupported visibility gap",
            INTEGRITY_VIOLATION_PROHIBITED_VISIBILITY_GAP: "prohibited visibility gap",
            INTEGRITY_VIOLATION_UNKNOWN_VISIBILITY_GAP: "unknown visibility gap",
            INTEGRITY_VIOLATION_MISSING_EVIDENCE_GAP: "missing evidence gap",
        },
        "classification_semantics": {
            INTEGRITY_CLASSIFICATION_SATISFIED: "all required evidence and deterministic guarantees are present with no unresolved violations",
            INTEGRITY_CLASSIFICATION_WARNING: "warnings and descriptive risks are visible while deterministic guarantees remain preserved",
            INTEGRITY_CLASSIFICATION_FAILED: "integrity violations are detected and remain fail-visible",
            INTEGRITY_CLASSIFICATION_BLOCKED: "governance, integrity preconditions, or boundary preservation blocks certification",
            INTEGRITY_CLASSIFICATION_UNSUPPORTED: "audit domain or evidence is outside supported deterministic scope",
            INTEGRITY_CLASSIFICATION_PROHIBITED: "requested integrity audit behavior violates non-execution or non-remediation boundaries",
            INTEGRITY_CLASSIFICATION_UNKNOWN: "audit semantics, provenance meaning, continuity meaning, or evidence meaning is uncertain",
            INTEGRITY_CLASSIFICATION_INCOMPLETE: "required domains, audit evidence, provenance, continuity, or explainability are missing",
        },
        "deterministic_guarantees": {
            "integrity_serialization_stable": serialization["stable"],
            "integrity_hash_stable": hashing["stable"],
            "integrity_hash": hash_transition_integrity_report(integrity_report),
            "integrity_summary_hash": integrity_report.summary.deterministic_summary_hash,
            "serialization_first_length": serialization["first_length"],
            "serialization_second_length": serialization["second_length"],
            "hash_algorithm": hashing["hash_algorithm"],
        },
        "deterministic_guarantee_summary": {
            "outputs_are_deterministic": serialization["stable"] and hashing["stable"],
            "finding_order_is_stable": True,
            "violation_order_is_stable": True,
            "visibility_order_is_stable": True,
            "serialization_is_stable": serialization["stable"],
            "hashing_is_stable": hashing["stable"],
            "repeated_equivalent_audits_produce_equivalent_outputs": True,
        },
        "replay_guarantees": {
            "replay_safe_integrity_finding_count": validation["replay_safe_integrity_finding_count"],
            "replay_continuity_preserved_count": validation["replay_continuity_preserved_count"],
            "all_findings_have_replay_evidence": validation["replay_safe_integrity_finding_count"]
            == validation["integrity_finding_count"],
        },
        "rollback_guarantees": {
            "rollback_safe_integrity_finding_count": validation[
                "rollback_safe_integrity_finding_count"
            ],
            "rollback_continuity_preserved_count": validation["rollback_continuity_preserved_count"],
            "all_findings_have_rollback_evidence": validation["rollback_safe_integrity_finding_count"]
            == validation["integrity_finding_count"],
        },
        "provenance_guarantees": {
            "provenance_safe_integrity_finding_count": validation[
                "provenance_safe_integrity_finding_count"
            ],
            "provenance_continuity_preserved_count": validation[
                "provenance_continuity_preserved_count"
            ],
            "all_findings_preserve_provenance": validation["provenance_safe_integrity_finding_count"]
            == validation["integrity_finding_count"],
        },
        "explainability_guarantees": {
            "explainability_safe_integrity_finding_count": validation[
                "explainability_safe_integrity_finding_count"
            ],
            "explainability_continuity_preserved_count": validation[
                "explainability_continuity_preserved_count"
            ],
            "all_findings_have_explainability": validation["finding_not_fail_visible_count"] == 0,
            "all_violations_are_fail_visible": validation["violation_not_fail_visible_count"] == 0,
            "all_visibility_is_fail_visible": validation["visibility_not_fail_visible_count"] == 0,
        },
        "non_execution_guarantees": {
            "orchestration_execution_absent": not integrity_report.orchestration_execution_enabled,
            "transition_execution_absent": not integrity_report.transition_execution_enabled,
            "graph_traversal_absent": not integrity_report.graph_traversal_enabled,
            "routing_absent": not integrity_report.routing_enabled,
            "scheduling_absent": not integrity_report.scheduling_enabled,
            "dispatch_absent": not integrity_report.dispatch_enabled,
            "runtime_orchestration_engine_absent": not integrity_report.runtime_orchestration_engine_enabled,
            "runtime_mutation_absent": not integrity_report.runtime_mutation_enabled,
            "authorization_absent": not integrity_report.authorization_enabled,
            "approval_absent": not integrity_report.approval_enabled,
            "optimization_absent": not integrity_report.optimization_enabled,
            "recommendation_absent": not integrity_report.recommendation_enabled,
            "ranking_absent": not integrity_report.ranking_enabled,
            "scoring_absent": not integrity_report.scoring_enabled,
            "selection_absent": not integrity_report.selection_enabled,
            "remediation_absent": not integrity_report.remediation_enabled,
            "repair_absent": not integrity_report.repair_enabled,
            "automatic_remediation_absent": not integrity_report.automatic_remediation_enabled,
            "automatic_repair_absent": not integrity_report.automatic_repair_enabled,
            "hidden_fallback_absent": not integrity_report.hidden_fallback_enabled,
            "silent_correction_absent": not integrity_report.silent_correction_enabled,
            "prioritization_absent": not integrity_report.prioritization_enabled,
            "weighted_severity_scoring_absent": not integrity_report.weighted_severity_scoring_enabled,
            "report_capability_leakage_count": validation["report_capability_leakage_count"],
        },
        "audit_only_guarantees": {
            "violations_are_descriptive_only": validation["violation_not_fail_visible_count"] == 0,
            "no_auto_remediation": validation["non_remediation_confirmation"],
            "no_auto_repair": validation["non_remediation_confirmation"],
            "no_recommendation_behavior": not integrity_report.recommendation_enabled,
            "no_ranking_behavior": not integrity_report.ranking_enabled,
            "no_scoring_behavior": not integrity_report.scoring_enabled,
            "no_selection_behavior": not integrity_report.selection_enabled,
            "non_selective_confirmation": validation["non_selective_confirmation"],
        },
        "integrity_report": export_transition_integrity_report(integrity_report),
        "explicit_limitations": [
            "v3.9 Phase 8 transition integrity enforcement is audit-only",
            "v3.9 Phase 8 does not enable orchestration execution",
            "v3.9 Phase 8 does not enable transition execution",
            "v3.9 Phase 8 does not enable remediation or repair",
            "v3.9 Phase 8 does not enable routing, scheduling, dispatch, or traversal",
            "v3.9 Phase 8 does not enable authorization or approval",
            "v3.9 Phase 8 does not enable recommendations",
            "v3.9 Phase 8 does not enable ranking, scoring, or selection",
            "v3.9 Phase 8 does not prioritize or weight violations",
            "v3.9 Phase 8 does not mutate transition evidence",
        ],
        "summary": {
            "integrity_report_status": integrity_report.report_status,
            "validation_error_count": validation["validation_error_count"],
            "deterministic_serialization_verified": serialization["stable"],
            "deterministic_hashing_verified": hashing["stable"],
            "integrity_satisfied_count": validation["integrity_satisfied_count"],
            "integrity_warning_count": validation["integrity_warning_count"],
            "integrity_failed_count": validation["integrity_failed_count"],
            "blocked_count": validation["blocked_count"],
            "unsupported_count": validation["unsupported_count"],
            "prohibited_count": validation["prohibited_count"],
            "unknown_count": validation["unknown_count"],
            "incomplete_count": validation["incomplete_count"],
            "integrity_finding_count": validation["integrity_finding_count"],
            "integrity_violation_count": validation["integrity_violation_count"],
            "hidden_finding_violation_count": validation["hidden_finding_violation_count"],
            "hidden_risk_violation_count": validation["hidden_risk_violation_count"],
            "hidden_non_safe_state_violation_count": validation[
                "hidden_non_safe_state_violation_count"
            ],
            "missing_evidence_violation_count": validation["missing_evidence_violation_count"],
            "provenance_gap_count": validation["provenance_gap_count"],
            "replay_gap_count": validation["replay_gap_count"],
            "rollback_gap_count": validation["rollback_gap_count"],
            "explainability_gap_count": validation["explainability_gap_count"],
            "aggregation_integrity_gap_count": validation["aggregation_integrity_gap_count"],
            "execution_boundary_leakage_count": validation["execution_boundary_leakage_count"],
            "recommendation_leakage_count": validation["recommendation_leakage_count"],
            "ranking_leakage_count": validation["ranking_leakage_count"],
            "scoring_leakage_count": validation["scoring_leakage_count"],
            "selection_leakage_count": validation["selection_leakage_count"],
            "mutation_leakage_count": validation["mutation_leakage_count"],
            "visibility_gap_count": validation["visibility_gap_count"],
            "replay_verified": validation["replay_safe_integrity_finding_count"]
            == validation["integrity_finding_count"],
            "rollback_verified": validation["rollback_safe_integrity_finding_count"]
            == validation["integrity_finding_count"],
            "provenance_verified": validation["provenance_safe_integrity_finding_count"]
            == validation["integrity_finding_count"],
            "explainability_verified": validation["finding_not_fail_visible_count"] == 0,
            "violation_visibility_verified": validation["violation_not_fail_visible_count"] == 0,
            "visibility_verified": validation["visibility_not_fail_visible_count"] == 0,
            "non_executable_verified": integrity_report.non_executable,
            "orchestration_boundaries_enforced": validation["report_capability_leakage_count"] == 0,
            "non_remediation_verified": validation["non_remediation_confirmation"],
            "descriptive_audit_verified": validation["non_selective_confirmation"],
            "source_artifact_continuity_preserved": present_source_artifact_count == source_artifact_count,
        },
    }
    report["deterministic_report_hash"] = deterministic_hash(
        {key: value for key, value in report.items() if key != "deterministic_report_hash"}
    )
    return report


def write_transition_integrity_markdown_report(report: dict[str, Any], output_path: Path) -> None:
    lines = [
        "# v3.9 Transition Integrity Enforcement",
        "",
        "## What Phase 8 Adds",
        "",
        "v3.9 Phase 8 audits the full transition intelligence chain for integrity problems, hidden risk, hidden behavior, missing continuity, missing provenance, and prohibited capability leakage.",
        "",
        "Integrity enforcement is audit-only and evidence-only. It detects and reports violations without mutating, repairing, approving, or authorizing transition evidence.",
        "",
        "This phase does NOT enable orchestration execution, traversal, routing, scheduling, dispatch, optimization, recommendation, ranking, scoring, selection, authorization, approval, remediation, repair, or runtime mutation.",
        "",
        "## Integrity Enforcement Is Not Remediation",
        "",
        "Integrity enforcement produces deterministic findings and violation records. It does not auto-fix evidence, silently correct state, apply fallback behavior, certify production readiness, or imply approval.",
        "",
        "## Hidden Finding And Risk Detection",
        "",
        "Hidden finding, hidden risk, and hidden non-safe-state violations are represented as explicit fail-visible violation records.",
        "",
        "## Continuity And Provenance Gaps",
        "",
        "Replay, rollback, provenance, and explainability gaps are detected through deterministic continuity references and surfaced without repair behavior.",
        "",
        "## Capability Leakage Detection",
        "",
        "Execution-boundary, mutation, recommendation, ranking, scoring, and selection leakage are detected as descriptive violations. They are not enabled by the report.",
        "",
        "## Visibility Gaps",
        "",
        "Unsupported, prohibited, unknown, and missing-evidence visibility gaps remain explicit and fail-visible.",
        "",
        "## Builds On Aggregation",
        "",
        "Phase 8 builds on transition intelligence aggregation and audits the aggregated evidence chain without changing aggregation behavior.",
        "",
        "## Integrity Totals",
        "",
        f"- Integrity satisfied: `{report['summary']['integrity_satisfied_count']}`",
        f"- Integrity warning: `{report['summary']['integrity_warning_count']}`",
        f"- Integrity failed: `{report['summary']['integrity_failed_count']}`",
        f"- Blocked: `{report['summary']['blocked_count']}`",
        f"- Unsupported: `{report['summary']['unsupported_count']}`",
        f"- Prohibited: `{report['summary']['prohibited_count']}`",
        f"- Unknown: `{report['summary']['unknown_count']}`",
        f"- Incomplete: `{report['summary']['incomplete_count']}`",
        f"- Integrity findings: `{report['summary']['integrity_finding_count']}`",
        f"- Integrity violations: `{report['summary']['integrity_violation_count']}`",
        "",
        "## Violation Totals",
        "",
        f"- Hidden finding violations: `{report['summary']['hidden_finding_violation_count']}`",
        f"- Hidden risk violations: `{report['summary']['hidden_risk_violation_count']}`",
        f"- Hidden non-safe state violations: `{report['summary']['hidden_non_safe_state_violation_count']}`",
        f"- Missing evidence violations: `{report['summary']['missing_evidence_violation_count']}`",
        f"- Provenance gaps: `{report['summary']['provenance_gap_count']}`",
        f"- Replay gaps: `{report['summary']['replay_gap_count']}`",
        f"- Rollback gaps: `{report['summary']['rollback_gap_count']}`",
        f"- Explainability gaps: `{report['summary']['explainability_gap_count']}`",
        f"- Aggregation integrity gaps: `{report['summary']['aggregation_integrity_gap_count']}`",
        f"- Execution-boundary leakage: `{report['summary']['execution_boundary_leakage_count']}`",
        f"- Recommendation leakage: `{report['summary']['recommendation_leakage_count']}`",
        f"- Ranking leakage: `{report['summary']['ranking_leakage_count']}`",
        f"- Scoring leakage: `{report['summary']['scoring_leakage_count']}`",
        f"- Selection leakage: `{report['summary']['selection_leakage_count']}`",
        f"- Mutation leakage: `{report['summary']['mutation_leakage_count']}`",
        f"- Visibility gaps: `{report['summary']['visibility_gap_count']}`",
        "",
        "## Deterministic Guarantees",
        "",
        f"- Integrity report status: `{report['summary']['integrity_report_status']}`",
        f"- Validation errors: `{report['summary']['validation_error_count']}`",
        f"- Serialization stable: `{report['summary']['deterministic_serialization_verified']}`",
        f"- Hash stable: `{report['summary']['deterministic_hashing_verified']}`",
        f"- Integrity hash: `{report['deterministic_guarantees']['integrity_hash']}`",
        f"- Integrity summary hash: `{report['deterministic_guarantees']['integrity_summary_hash']}`",
        f"- Report hash: `{report['deterministic_report_hash']}`",
        "",
        "## Replay Rollback Provenance And Explainability",
        "",
        f"- Replay verified: `{report['summary']['replay_verified']}`",
        f"- Rollback verified: `{report['summary']['rollback_verified']}`",
        f"- Provenance verified: `{report['summary']['provenance_verified']}`",
        f"- Explainability verified: `{report['summary']['explainability_verified']}`",
        f"- Violation visibility verified: `{report['summary']['violation_visibility_verified']}`",
        f"- Non-remediation verified: `{report['summary']['non_remediation_verified']}`",
        "",
        "## What Remains Prohibited",
        "",
        "- Orchestration execution.",
        "- Transition execution.",
        "- Graph traversal.",
        "- Routing.",
        "- Scheduling.",
        "- Dispatch.",
        "- Runtime orchestration engines.",
        "- Runtime mutation.",
        "- Authorization systems.",
        "- Approval systems.",
        "- Optimization.",
        "- Recommendations.",
        "- Ranking.",
        "- Scoring.",
        "- Selection.",
        "- Remediation.",
        "- Repair.",
        "- Automatic remediation.",
        "- Automatic repair.",
        "- Silent correction.",
        "- Hidden fallback.",
        "- Weighted severity scoring.",
        "- Prioritization ranking.",
        "- Production behavior.",
        "",
        "## Generated Evidence",
        "",
        "- JSON report: `docs/generated/v3_9_transition_integrity_enforcement_report.json`",
        "- This migration note: `docs/migration/V3_9_TRANSITION_INTEGRITY_ENFORCEMENT.md`",
    ]
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _source_artifact_status(repo_root: Path, relative_path: str) -> dict[str, Any]:
    artifact_path = repo_root / relative_path
    if not artifact_path.exists():
        return {
            "path": relative_path,
            "present": False,
            "artifact_hash": "",
        }
    text = artifact_path.read_text(encoding="utf-8")
    try:
        payload: Any = json.loads(text)
    except json.JSONDecodeError:
        payload = {"raw_text": text}
    return {
        "path": relative_path,
        "present": True,
        "artifact_hash": deterministic_hash(payload),
    }
