"""Report builders for deterministic v3.9 transition scenario intelligence."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .transition_foundation_hashing import deterministic_hash
from .transition_scenario_engine import build_v3_9_transition_scenario
from .transition_scenario_models import (
    SCENARIO_CLASSIFICATION_BLOCKED,
    SCENARIO_CLASSIFICATION_INCOMPLETE,
    SCENARIO_CLASSIFICATION_MODELED,
    SCENARIO_CLASSIFICATION_PARTIALLY_MODELED,
    SCENARIO_CLASSIFICATION_PROHIBITED,
    SCENARIO_CLASSIFICATION_UNKNOWN,
    SCENARIO_CLASSIFICATION_UNMODELED,
    SCENARIO_CLASSIFICATION_UNSUPPORTED,
    SCENARIO_FINDING_COMPARISON,
    SCENARIO_FINDING_CONTINUITY,
    SCENARIO_FINDING_EXPLAINABILITY,
    SCENARIO_FINDING_GOVERNANCE,
    SCENARIO_FINDING_INTEGRITY,
    SCENARIO_FINDING_MISSING_EVIDENCE,
    SCENARIO_FINDING_PROHIBITED,
    SCENARIO_FINDING_PROVENANCE,
    SCENARIO_FINDING_RISK_VISIBILITY,
    SCENARIO_FINDING_SESSION_EVIDENCE,
    SCENARIO_FINDING_UNCERTAINTY,
    SCENARIO_FINDING_UNSUPPORTED,
    SCENARIO_FINDING_VARIANT,
    SCENARIO_RISK_CONTINUITY,
    SCENARIO_RISK_EXPLAINABILITY,
    SCENARIO_RISK_GOVERNANCE,
    SCENARIO_RISK_INTEGRITY,
    SCENARIO_RISK_MISSING_EVIDENCE,
    SCENARIO_RISK_PROHIBITED_CAPABILITY,
    SCENARIO_RISK_PROVENANCE,
    SCENARIO_RISK_UNCERTAINTY,
    SCENARIO_RISK_UNSUPPORTED_DOMAIN,
    export_transition_scenario_report,
)
from .transition_scenario_serialization import (
    hash_transition_scenario_report,
    validate_transition_scenario_hash_stability,
    validate_transition_scenario_serialization_stability,
)
from .transition_scenario_validation import validate_transition_scenario_report


DETERMINISTIC_GENERATED_AT = "2026-05-16T00:00:00+00:00"

SOURCE_ARTIFACT_PATHS: tuple[str, ...] = (
    "docs/generated/v3_9_transition_foundations_report.json",
    "docs/migration/V3_9_TRANSITION_FOUNDATIONS.md",
    "docs/generated/v3_9_transition_boundary_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_BOUNDARY_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_compatibility_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_COMPATIBILITY_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_evaluation_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_EVALUATION_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_session_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_SESSION_INTELLIGENCE.md",
)


def build_v3_9_transition_scenario_intelligence_report(repo_root: Path | None = None) -> dict[str, Any]:
    root = repo_root or Path(__file__).resolve().parents[3]
    scenario_report = build_v3_9_transition_scenario()
    validation = validate_transition_scenario_report(scenario_report)
    serialization = validate_transition_scenario_serialization_stability(scenario_report)
    hashing = validate_transition_scenario_hash_stability(scenario_report)
    source_artifacts = [_source_artifact_status(root, path) for path in SOURCE_ARTIFACT_PATHS]
    source_artifact_count = len(source_artifacts)
    present_source_artifact_count = sum(1 for artifact in source_artifacts if artifact["present"])
    report = {
        "schema_version": "v3_9.transition_scenario_intelligence_report.1",
        "generated_at": DETERMINISTIC_GENERATED_AT,
        "phase_name": "v3.9_transition_scenario_intelligence",
        "repo_root": str(root),
        "architectural_purpose": "deterministic hypothetical transition scenario evidence reasoning without transition execution",
        "scenario_report_status": scenario_report.report_status,
        "source_foundation_id": scenario_report.source_foundation_id,
        "source_boundary_report_id": scenario_report.source_boundary_report_id,
        "source_compatibility_report_id": scenario_report.source_compatibility_report_id,
        "source_evaluation_report_id": scenario_report.source_evaluation_report_id,
        "source_session_report_id": scenario_report.source_session_report_id,
        "non_executable": scenario_report.non_executable,
        "orchestration_execution_enabled": scenario_report.orchestration_execution_enabled,
        "transition_execution_enabled": scenario_report.transition_execution_enabled,
        "graph_traversal_enabled": scenario_report.graph_traversal_enabled,
        "routing_enabled": scenario_report.routing_enabled,
        "scheduling_enabled": scenario_report.scheduling_enabled,
        "dispatch_enabled": scenario_report.dispatch_enabled,
        "runtime_orchestration_engine_enabled": scenario_report.runtime_orchestration_engine_enabled,
        "runtime_mutation_enabled": scenario_report.runtime_mutation_enabled,
        "authorization_enabled": scenario_report.authorization_enabled,
        "approval_enabled": scenario_report.approval_enabled,
        "optimization_enabled": scenario_report.optimization_enabled,
        "recommendation_enabled": scenario_report.recommendation_enabled,
        "ranking_enabled": scenario_report.ranking_enabled,
        "scoring_enabled": scenario_report.scoring_enabled,
        "selection_enabled": scenario_report.selection_enabled,
        "autonomous_behavior_enabled": scenario_report.autonomous_behavior_enabled,
        "callable_orchestration_flow_enabled": scenario_report.callable_orchestration_flow_enabled,
        "transition_handler_enabled": scenario_report.transition_handler_enabled,
        "runtime_state_machine_enabled": scenario_report.runtime_state_machine_enabled,
        "production_behavior_enabled": scenario_report.production_behavior_enabled,
        "hidden_fallback_enabled": scenario_report.hidden_fallback_enabled,
        "silent_correction_enabled": scenario_report.silent_correction_enabled,
        "source_artifacts": source_artifacts,
        "source_artifact_totals": {
            "source_artifact_count": source_artifact_count,
            "present_source_artifact_count": present_source_artifact_count,
            "missing_source_artifact_count": source_artifact_count - present_source_artifact_count,
            "source_artifact_continuity_preserved": present_source_artifact_count == source_artifact_count,
        },
        "scenario_classification_counts": dict(scenario_report.summary.classification_counts),
        "scenario_finding_counts": dict(scenario_report.summary.finding_category_counts),
        "scenario_risk_counts": dict(scenario_report.summary.risk_category_counts),
        "scenario_totals": {
            "scenario_input_count": validation["scenario_input_count"],
            "scenario_record_count": validation["scenario_record_count"],
            "scenario_variant_count": validation["scenario_variant_count"],
            "scenario_comparison_count": validation["scenario_comparison_count"],
            "scenario_risk_count": validation["scenario_risk_count"],
            "scenario_finding_count": validation["scenario_finding_count"],
            "modeled_count": validation["modeled_count"],
            "partially_modeled_count": validation["partially_modeled_count"],
            "unmodeled_count": validation["unmodeled_count"],
            "blocked_count": validation["blocked_count"],
            "unsupported_count": validation["unsupported_count"],
            "prohibited_count": validation["prohibited_count"],
            "unknown_count": validation["unknown_count"],
            "incomplete_count": validation["incomplete_count"],
            "governance_risk_count": validation["governance_risk_count"],
            "uncertainty_risk_count": validation["uncertainty_risk_count"],
            "missing_evidence_risk_count": validation["missing_evidence_risk_count"],
            "hidden_scenario_finding_count": validation["hidden_scenario_finding_count"],
            "hidden_risk_count": validation["hidden_risk_count"],
            "execution_boundary_violation_count": validation["execution_boundary_violation_count"],
            "recommendation_ranking_scoring_selection_violation_count": validation[
                "recommendation_ranking_scoring_selection_violation_count"
            ],
        },
        "deterministic_guarantees": {
            "scenario_serialization_stable": serialization["stable"],
            "scenario_hash_stable": hashing["stable"],
            "scenario_hash": hash_transition_scenario_report(scenario_report),
            "scenario_summary_hash": scenario_report.summary.deterministic_summary_hash,
            "serialization_first_length": serialization["first_length"],
            "serialization_second_length": serialization["second_length"],
            "hash_algorithm": hashing["hash_algorithm"],
        },
        "deterministic_guarantee_summary": {
            "outputs_are_deterministic": serialization["stable"] and hashing["stable"],
            "variant_order_is_stable": True,
            "finding_order_is_stable": True,
            "risk_order_is_stable": True,
            "comparison_order_is_stable": True,
            "serialization_is_stable": serialization["stable"],
            "hashing_is_stable": hashing["stable"],
            "repeated_equivalent_scenario_inputs_produce_equivalent_outputs": True,
        },
        "replay_guarantees": {
            "replay_safe_scenario_finding_count": validation["replay_safe_scenario_finding_count"],
            "replay_safe_risk_count": validation["replay_safe_risk_count"],
            "replay_continuity_preserved_count": validation["replay_continuity_preserved_count"],
            "all_findings_have_replay_evidence": validation["replay_safe_scenario_finding_count"]
            == validation["scenario_finding_count"],
        },
        "rollback_guarantees": {
            "rollback_safe_scenario_finding_count": validation["rollback_safe_scenario_finding_count"],
            "rollback_safe_risk_count": validation["rollback_safe_risk_count"],
            "rollback_continuity_preserved_count": validation["rollback_continuity_preserved_count"],
            "all_findings_have_rollback_evidence": validation["rollback_safe_scenario_finding_count"]
            == validation["scenario_finding_count"],
        },
        "provenance_guarantees": {
            "provenance_safe_scenario_finding_count": validation["provenance_safe_scenario_finding_count"],
            "provenance_safe_risk_count": validation["provenance_safe_risk_count"],
            "provenance_continuity_preserved_count": validation["provenance_continuity_preserved_count"],
            "all_findings_preserve_provenance": validation["provenance_safe_scenario_finding_count"]
            == validation["scenario_finding_count"],
        },
        "explainability_guarantees": {
            "explainability_safe_scenario_finding_count": validation[
                "explainability_safe_scenario_finding_count"
            ],
            "explainability_safe_risk_count": validation["explainability_safe_risk_count"],
            "explainability_continuity_preserved_count": validation[
                "explainability_continuity_preserved_count"
            ],
            "all_findings_have_explainability": validation["finding_not_fail_visible_count"] == 0,
            "all_risks_are_fail_visible": validation["risk_not_fail_visible_count"] == 0,
            "hidden_scenario_finding_count": validation["hidden_scenario_finding_count"],
            "hidden_risk_count": validation["hidden_risk_count"],
        },
        "non_execution_guarantees": {
            "orchestration_execution_absent": not scenario_report.orchestration_execution_enabled,
            "transition_execution_absent": not scenario_report.transition_execution_enabled,
            "graph_traversal_absent": not scenario_report.graph_traversal_enabled,
            "routing_absent": not scenario_report.routing_enabled,
            "scheduling_absent": not scenario_report.scheduling_enabled,
            "dispatch_absent": not scenario_report.dispatch_enabled,
            "runtime_orchestration_engine_absent": not scenario_report.runtime_orchestration_engine_enabled,
            "runtime_mutation_absent": not scenario_report.runtime_mutation_enabled,
            "authorization_absent": not scenario_report.authorization_enabled,
            "approval_absent": not scenario_report.approval_enabled,
            "optimization_absent": not scenario_report.optimization_enabled,
            "recommendation_absent": not scenario_report.recommendation_enabled,
            "ranking_absent": not scenario_report.ranking_enabled,
            "scoring_absent": not scenario_report.scoring_enabled,
            "selection_absent": not scenario_report.selection_enabled,
            "autonomous_behavior_absent": not scenario_report.autonomous_behavior_enabled,
            "callable_orchestration_flow_absent": not scenario_report.callable_orchestration_flow_enabled,
            "transition_handler_absent": not scenario_report.transition_handler_enabled,
            "runtime_state_machine_absent": not scenario_report.runtime_state_machine_enabled,
            "production_behavior_absent": not scenario_report.production_behavior_enabled,
            "hidden_fallback_absent": not scenario_report.hidden_fallback_enabled,
            "silent_correction_absent": not scenario_report.silent_correction_enabled,
            "report_execution_capability_violation_count": validation[
                "report_execution_capability_violation_count"
            ],
        },
        "non_selective_comparison_guarantees": {
            "comparisons_are_descriptive_only": validation["comparison_selection_violation_count"] == 0,
            "no_winner_selected": validation["comparison_selection_violation_count"] == 0,
            "no_recommendation_behavior": not scenario_report.recommendation_enabled,
            "no_ranking_behavior": not scenario_report.ranking_enabled,
            "no_scoring_behavior": not scenario_report.scoring_enabled,
            "no_selection_behavior": not scenario_report.selection_enabled,
            "risk_records_are_descriptive_not_scored": validation["risk_not_fail_visible_count"] == 0,
            "non_selective_confirmation": validation["non_selective_confirmation"],
        },
        "classification_semantics": {
            SCENARIO_CLASSIFICATION_MODELED: "scenario identity, session evidence, variants, provenance, replay, rollback, and explainability are present with no non-safe markers",
            SCENARIO_CLASSIFICATION_PARTIALLY_MODELED: "at least one scenario variant is modeled while visible guarantees remain missing or failed",
            SCENARIO_CLASSIFICATION_UNMODELED: "scenario cannot be deterministically modeled under current coverage",
            SCENARIO_CLASSIFICATION_BLOCKED: "governance, integrity, or execution-boundary preservation blocks scenario modeling",
            SCENARIO_CLASSIFICATION_UNSUPPORTED: "scenario domain or evidence is outside supported deterministic scope",
            SCENARIO_CLASSIFICATION_PROHIBITED: "requested scenario modeling behavior violates non-execution or non-selection boundaries",
            SCENARIO_CLASSIFICATION_UNKNOWN: "scenario semantics, provenance meaning, continuity meaning, or evidence meaning is uncertain",
            SCENARIO_CLASSIFICATION_INCOMPLETE: "required scenario identity, session evidence, variants, provenance, continuity, or explainability evidence is missing",
        },
        "finding_semantics": {
            SCENARIO_FINDING_SESSION_EVIDENCE: "session evidence packaging finding",
            SCENARIO_FINDING_VARIANT: "scenario variant finding",
            SCENARIO_FINDING_COMPARISON: "non-selective scenario comparison finding",
            SCENARIO_FINDING_RISK_VISIBILITY: "descriptive scenario risk visibility finding",
            SCENARIO_FINDING_CONTINUITY: "scenario continuity finding",
            SCENARIO_FINDING_PROVENANCE: "scenario provenance finding",
            SCENARIO_FINDING_EXPLAINABILITY: "scenario explainability finding",
            SCENARIO_FINDING_GOVERNANCE: "scenario governance finding",
            SCENARIO_FINDING_INTEGRITY: "scenario integrity finding",
            SCENARIO_FINDING_UNSUPPORTED: "unsupported scenario finding",
            SCENARIO_FINDING_PROHIBITED: "prohibited scenario behavior finding",
            SCENARIO_FINDING_MISSING_EVIDENCE: "missing scenario evidence finding",
            SCENARIO_FINDING_UNCERTAINTY: "uncertain scenario evidence finding",
        },
        "risk_semantics": {
            SCENARIO_RISK_PROVENANCE: "descriptive provenance risk",
            SCENARIO_RISK_CONTINUITY: "descriptive continuity risk",
            SCENARIO_RISK_EXPLAINABILITY: "descriptive explainability risk",
            SCENARIO_RISK_UNSUPPORTED_DOMAIN: "descriptive unsupported-domain risk",
            SCENARIO_RISK_PROHIBITED_CAPABILITY: "descriptive prohibited-capability risk",
            SCENARIO_RISK_MISSING_EVIDENCE: "descriptive missing-evidence risk",
            SCENARIO_RISK_UNCERTAINTY: "descriptive uncertainty risk",
            SCENARIO_RISK_GOVERNANCE: "descriptive governance risk",
            SCENARIO_RISK_INTEGRITY: "descriptive integrity risk",
        },
        "scenario_report": export_transition_scenario_report(scenario_report),
        "explicit_limitations": [
            "v3.9 Phase 6 transition scenario intelligence is non-executable",
            "v3.9 Phase 6 does not enable orchestration execution",
            "v3.9 Phase 6 does not enable transition execution",
            "v3.9 Phase 6 does not enable graph traversal",
            "v3.9 Phase 6 does not enable routing, scheduling, or dispatch",
            "v3.9 Phase 6 does not enable runtime orchestration engines",
            "v3.9 Phase 6 does not enable runtime mutation",
            "v3.9 Phase 6 does not enable authorization or approval systems",
            "v3.9 Phase 6 does not enable optimization or recommendations",
            "v3.9 Phase 6 does not enable ranking, scoring, or selection",
            "v3.9 Phase 6 does not choose a best scenario",
            "v3.9 Phase 6 does not assign scenario scores",
            "v3.9 Phase 6 does not rank scenarios",
            "v3.9 Phase 6 does not recommend scenarios",
            "v3.9 Phase 6 does not enable production behavior",
        ],
        "summary": {
            "scenario_report_status": scenario_report.report_status,
            "validation_error_count": validation["validation_error_count"],
            "deterministic_serialization_verified": serialization["stable"],
            "deterministic_hashing_verified": hashing["stable"],
            "modeled_count": validation["modeled_count"],
            "partially_modeled_count": validation["partially_modeled_count"],
            "unmodeled_count": validation["unmodeled_count"],
            "blocked_count": validation["blocked_count"],
            "unsupported_count": validation["unsupported_count"],
            "prohibited_count": validation["prohibited_count"],
            "unknown_count": validation["unknown_count"],
            "incomplete_count": validation["incomplete_count"],
            "scenario_finding_count": validation["scenario_finding_count"],
            "scenario_variant_count": validation["scenario_variant_count"],
            "scenario_comparison_count": validation["scenario_comparison_count"],
            "scenario_risk_count": validation["scenario_risk_count"],
            "governance_risk_count": validation["governance_risk_count"],
            "uncertainty_risk_count": validation["uncertainty_risk_count"],
            "missing_evidence_risk_count": validation["missing_evidence_risk_count"],
            "hidden_scenario_finding_count": validation["hidden_scenario_finding_count"],
            "hidden_risk_count": validation["hidden_risk_count"],
            "execution_boundary_violation_count": validation["execution_boundary_violation_count"],
            "recommendation_ranking_scoring_selection_violation_count": validation[
                "recommendation_ranking_scoring_selection_violation_count"
            ],
            "report_execution_capability_violation_count": validation[
                "report_execution_capability_violation_count"
            ],
            "replay_verified": validation["replay_safe_scenario_finding_count"]
            == validation["scenario_finding_count"],
            "rollback_verified": validation["rollback_safe_scenario_finding_count"]
            == validation["scenario_finding_count"],
            "provenance_verified": validation["provenance_safe_scenario_finding_count"]
            == validation["scenario_finding_count"],
            "explainability_verified": validation["finding_not_fail_visible_count"] == 0,
            "risk_visibility_verified": validation["risk_not_fail_visible_count"] == 0,
            "non_executable_verified": scenario_report.non_executable,
            "orchestration_boundaries_enforced": validation["report_execution_capability_violation_count"] == 0,
            "non_selective_comparison_verified": validation["non_selective_confirmation"],
            "source_artifact_continuity_preserved": present_source_artifact_count == source_artifact_count,
        },
    }
    report["deterministic_report_hash"] = deterministic_hash(
        {key: value for key, value in report.items() if key != "deterministic_report_hash"}
    )
    return report


def write_transition_scenario_markdown_report(report: dict[str, Any], output_path: Path) -> None:
    lines = [
        "# v3.9 Transition Scenario Intelligence",
        "",
        "## What Phase 6 Adds",
        "",
        "v3.9 Phase 6 models hypothetical transition scenarios from deterministic transition session evidence.",
        "",
        "It records scenario variants, descriptive risks, non-selective comparisons, findings, evidence, provenance, continuity, and visibility without enabling execution behavior.",
        "",
        "This phase does NOT enable orchestration execution, traversal, routing, scheduling, dispatch, optimization, recommendation, ranking, scoring, selection, authorization, approval, or runtime mutation.",
        "",
        "## Scenarios Are Not Execution",
        "",
        "A transition scenario is a deterministic evidence model. It does not execute a transition, authorize a transition, traverse a graph, choose a route, schedule dispatch, approve behavior, mutate runtime state, or produce a production pathway.",
        "",
        "## Hypothetical Variants",
        "",
        "Scenario variants are immutable evidence references derived from session evidence. They preserve deterministic ordering, provenance references, continuity references, and explainability references.",
        "",
        "## Non-Selective Comparisons",
        "",
        "Scenario comparisons can describe matching evidence, differing evidence, missing evidence, continuity differences, provenance differences, explainability differences, risk differences, and classification differences.",
        "",
        "Comparisons do not choose a best scenario, rank scenarios, score scenarios, recommend scenarios, optimize selection, or imply approval.",
        "",
        "## Descriptive Risks",
        "",
        "Scenario risks are descriptive evidence records only. They do not contain numeric rankings, priority scores, recommendation outputs, or selection outcomes.",
        "",
        "## Fail-Visible Findings",
        "",
        "Every scenario finding includes a reason, evidence reference, provenance reference, continuity reference, and explainability message.",
        "",
        "No scenario state, risk, or comparison is hidden, silently corrected, or promoted from partial or non-modeled to modeled.",
        "",
        "## Governance-Safe Scenario Tracking",
        "",
        "Governance and integrity findings can block a scenario while preserving deterministic evidence, provenance, replay, rollback, and explainability continuity.",
        "",
        "## Builds On Session Intelligence",
        "",
        "Phase 6 consumes Phase 5 transition session outputs as scenario evidence references and packages hypothetical variants without changing session reasoning.",
        "",
        "## Scenario Totals",
        "",
        f"- Modeled: `{report['summary']['modeled_count']}`",
        f"- Partially modeled: `{report['summary']['partially_modeled_count']}`",
        f"- Unmodeled: `{report['summary']['unmodeled_count']}`",
        f"- Blocked: `{report['summary']['blocked_count']}`",
        f"- Unsupported: `{report['summary']['unsupported_count']}`",
        f"- Prohibited: `{report['summary']['prohibited_count']}`",
        f"- Unknown: `{report['summary']['unknown_count']}`",
        f"- Incomplete: `{report['summary']['incomplete_count']}`",
        "",
        "## Evidence Totals",
        "",
        f"- Scenario findings: `{report['summary']['scenario_finding_count']}`",
        f"- Scenario variants: `{report['summary']['scenario_variant_count']}`",
        f"- Scenario comparisons: `{report['summary']['scenario_comparison_count']}`",
        f"- Scenario risks: `{report['summary']['scenario_risk_count']}`",
        f"- Governance risks: `{report['summary']['governance_risk_count']}`",
        f"- Uncertainty risks: `{report['summary']['uncertainty_risk_count']}`",
        f"- Missing-evidence risks: `{report['summary']['missing_evidence_risk_count']}`",
        f"- Hidden scenario findings: `{report['summary']['hidden_scenario_finding_count']}`",
        f"- Hidden risks: `{report['summary']['hidden_risk_count']}`",
        f"- Execution-boundary violation detections: `{report['summary']['execution_boundary_violation_count']}`",
        f"- Recommendation/ranking/scoring/selection violation detections: `{report['summary']['recommendation_ranking_scoring_selection_violation_count']}`",
        "",
        "## Deterministic Guarantees",
        "",
        f"- Scenario report status: `{report['summary']['scenario_report_status']}`",
        f"- Validation errors: `{report['summary']['validation_error_count']}`",
        f"- Serialization stable: `{report['summary']['deterministic_serialization_verified']}`",
        f"- Hash stable: `{report['summary']['deterministic_hashing_verified']}`",
        f"- Scenario hash: `{report['deterministic_guarantees']['scenario_hash']}`",
        f"- Scenario summary hash: `{report['deterministic_guarantees']['scenario_summary_hash']}`",
        f"- Report hash: `{report['deterministic_report_hash']}`",
        "",
        "## Replay Rollback Provenance And Explainability",
        "",
        f"- Replay verified: `{report['summary']['replay_verified']}`",
        f"- Rollback verified: `{report['summary']['rollback_verified']}`",
        f"- Provenance verified: `{report['summary']['provenance_verified']}`",
        f"- Explainability verified: `{report['summary']['explainability_verified']}`",
        f"- Risk visibility verified: `{report['summary']['risk_visibility_verified']}`",
        f"- Non-selective comparison verified: `{report['summary']['non_selective_comparison_verified']}`",
        "",
        "## What Remains Prohibited",
        "",
        "- Orchestration execution.",
        "- Transition execution.",
        "- Graph traversal.",
        "- Routing.",
        "- Scheduling.",
        "- Dispatch.",
        "- Runtime orchestration engines.",
        "- Runtime mutation.",
        "- Authorization systems.",
        "- Approval systems.",
        "- Optimization.",
        "- Recommendations.",
        "- Ranking.",
        "- Scoring.",
        "- Selection.",
        "- Autonomous behavior.",
        "- Callable orchestration flows.",
        "- Transition handlers.",
        "- Runtime state machines.",
        "- Production behavior.",
        "",
        "## Generated Evidence",
        "",
        "- JSON report: `docs/generated/v3_9_transition_scenario_intelligence_report.json`",
        "- This migration note: `docs/migration/V3_9_TRANSITION_SCENARIO_INTELLIGENCE.md`",
    ]
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _source_artifact_status(repo_root: Path, relative_path: str) -> dict[str, Any]:
    artifact_path = repo_root / relative_path
    if not artifact_path.exists():
        return {
            "path": relative_path,
            "present": False,
            "artifact_hash": "",
        }
    text = artifact_path.read_text(encoding="utf-8")
    try:
        payload: Any = json.loads(text)
    except json.JSONDecodeError:
        payload = {"raw_text": text}
    return {
        "path": relative_path,
        "present": True,
        "artifact_hash": deterministic_hash(payload),
    }
