"""Report builders for deterministic v3.9 transition intelligence aggregation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .transition_aggregation_engine import build_v3_9_transition_aggregation
from .transition_aggregation_models import (
    AGGREGATION_CLASSIFICATION_AGGREGATED,
    AGGREGATION_CLASSIFICATION_BLOCKED,
    AGGREGATION_CLASSIFICATION_INCOMPLETE,
    AGGREGATION_CLASSIFICATION_PARTIALLY_AGGREGATED,
    AGGREGATION_CLASSIFICATION_PROHIBITED,
    AGGREGATION_CLASSIFICATION_UNKNOWN,
    AGGREGATION_CLASSIFICATION_UNAGGREGATED,
    AGGREGATION_CLASSIFICATION_UNSUPPORTED,
    AGGREGATION_FINDING_BOUNDARY,
    AGGREGATION_FINDING_COMPATIBILITY,
    AGGREGATION_FINDING_CONTINUITY,
    AGGREGATION_FINDING_EVALUATION,
    AGGREGATION_FINDING_EXPLAINABILITY,
    AGGREGATION_FINDING_FOUNDATION,
    AGGREGATION_FINDING_GOVERNANCE,
    AGGREGATION_FINDING_INTEGRITY,
    AGGREGATION_FINDING_MISSING_EVIDENCE,
    AGGREGATION_FINDING_PROHIBITED,
    AGGREGATION_FINDING_PROVENANCE,
    AGGREGATION_FINDING_SCENARIO,
    AGGREGATION_FINDING_SESSION,
    AGGREGATION_FINDING_UNCERTAINTY,
    AGGREGATION_FINDING_UNSUPPORTED,
    AGGREGATION_FINDING_VISIBILITY,
    AGGREGATION_VISIBILITY_CONTINUITY,
    AGGREGATION_VISIBILITY_EXPLAINABILITY,
    AGGREGATION_VISIBILITY_FAIL_VISIBLE,
    AGGREGATION_VISIBILITY_GOVERNANCE,
    AGGREGATION_VISIBILITY_INTEGRITY,
    AGGREGATION_VISIBILITY_MISSING_EVIDENCE,
    AGGREGATION_VISIBILITY_PROHIBITED_STATE,
    AGGREGATION_VISIBILITY_PROVENANCE,
    AGGREGATION_VISIBILITY_SCENARIO_RISK,
    AGGREGATION_VISIBILITY_UNCERTAINTY,
    AGGREGATION_VISIBILITY_UNSUPPORTED_STATE,
    export_transition_aggregation_report,
)
from .transition_aggregation_serialization import (
    hash_transition_aggregation_report,
    validate_transition_aggregation_hash_stability,
    validate_transition_aggregation_serialization_stability,
)
from .transition_aggregation_validation import validate_transition_aggregation_report
from .transition_foundation_hashing import deterministic_hash


DETERMINISTIC_GENERATED_AT = "2026-05-16T00:00:00+00:00"

SOURCE_ARTIFACT_PATHS: tuple[str, ...] = (
    "docs/generated/v3_9_transition_foundations_report.json",
    "docs/migration/V3_9_TRANSITION_FOUNDATIONS.md",
    "docs/generated/v3_9_transition_boundary_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_BOUNDARY_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_compatibility_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_COMPATIBILITY_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_evaluation_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_EVALUATION_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_session_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_SESSION_INTELLIGENCE.md",
    "docs/generated/v3_9_transition_scenario_intelligence_report.json",
    "docs/migration/V3_9_TRANSITION_SCENARIO_INTELLIGENCE.md",
)


def build_v3_9_transition_intelligence_aggregation_report(repo_root: Path | None = None) -> dict[str, Any]:
    root = repo_root or Path(__file__).resolve().parents[3]
    aggregation_report = build_v3_9_transition_aggregation()
    validation = validate_transition_aggregation_report(aggregation_report)
    serialization = validate_transition_aggregation_serialization_stability(aggregation_report)
    hashing = validate_transition_aggregation_hash_stability(aggregation_report)
    source_artifacts = [_source_artifact_status(root, path) for path in SOURCE_ARTIFACT_PATHS]
    source_artifact_count = len(source_artifacts)
    present_source_artifact_count = sum(1 for artifact in source_artifacts if artifact["present"])
    report = {
        "schema_version": "v3_9.transition_intelligence_aggregation_report.1",
        "generated_at": DETERMINISTIC_GENERATED_AT,
        "phase_name": "v3.9_transition_intelligence_aggregation",
        "repo_root": str(root),
        "architectural_purpose": "deterministic descriptive transition intelligence aggregation without transition execution",
        "aggregation_report_status": aggregation_report.report_status,
        "source_foundation_id": aggregation_report.source_foundation_id,
        "source_boundary_report_id": aggregation_report.source_boundary_report_id,
        "source_compatibility_report_id": aggregation_report.source_compatibility_report_id,
        "source_evaluation_report_id": aggregation_report.source_evaluation_report_id,
        "source_session_report_id": aggregation_report.source_session_report_id,
        "source_scenario_report_id": aggregation_report.source_scenario_report_id,
        "non_executable": aggregation_report.non_executable,
        "orchestration_execution_enabled": aggregation_report.orchestration_execution_enabled,
        "transition_execution_enabled": aggregation_report.transition_execution_enabled,
        "graph_traversal_enabled": aggregation_report.graph_traversal_enabled,
        "routing_enabled": aggregation_report.routing_enabled,
        "scheduling_enabled": aggregation_report.scheduling_enabled,
        "dispatch_enabled": aggregation_report.dispatch_enabled,
        "runtime_orchestration_engine_enabled": aggregation_report.runtime_orchestration_engine_enabled,
        "runtime_mutation_enabled": aggregation_report.runtime_mutation_enabled,
        "authorization_enabled": aggregation_report.authorization_enabled,
        "approval_enabled": aggregation_report.approval_enabled,
        "optimization_enabled": aggregation_report.optimization_enabled,
        "recommendation_enabled": aggregation_report.recommendation_enabled,
        "ranking_enabled": aggregation_report.ranking_enabled,
        "scoring_enabled": aggregation_report.scoring_enabled,
        "selection_enabled": aggregation_report.selection_enabled,
        "autonomous_behavior_enabled": aggregation_report.autonomous_behavior_enabled,
        "callable_orchestration_flow_enabled": aggregation_report.callable_orchestration_flow_enabled,
        "transition_handler_enabled": aggregation_report.transition_handler_enabled,
        "runtime_state_machine_enabled": aggregation_report.runtime_state_machine_enabled,
        "production_behavior_enabled": aggregation_report.production_behavior_enabled,
        "hidden_fallback_enabled": aggregation_report.hidden_fallback_enabled,
        "silent_correction_enabled": aggregation_report.silent_correction_enabled,
        "prioritization_enabled": aggregation_report.prioritization_enabled,
        "weighting_enabled": aggregation_report.weighting_enabled,
        "source_artifacts": source_artifacts,
        "source_artifact_totals": {
            "source_artifact_count": source_artifact_count,
            "present_source_artifact_count": present_source_artifact_count,
            "missing_source_artifact_count": source_artifact_count - present_source_artifact_count,
            "source_artifact_continuity_preserved": present_source_artifact_count == source_artifact_count,
        },
        "aggregation_classification_counts": dict(aggregation_report.summary.classification_counts),
        "aggregation_finding_counts": dict(aggregation_report.summary.finding_category_counts),
        "aggregation_visibility_counts": dict(aggregation_report.summary.visibility_category_counts),
        "aggregation_totals": {
            "aggregation_input_count": validation["aggregation_input_count"],
            "aggregation_record_count": validation["aggregation_record_count"],
            "aggregation_finding_count": validation["aggregation_finding_count"],
            "aggregation_visibility_count": validation["aggregation_visibility_count"],
            "aggregated_count": validation["aggregated_count"],
            "partially_aggregated_count": validation["partially_aggregated_count"],
            "unaggregated_count": validation["unaggregated_count"],
            "blocked_count": validation["blocked_count"],
            "unsupported_count": validation["unsupported_count"],
            "prohibited_count": validation["prohibited_count"],
            "unknown_count": validation["unknown_count"],
            "incomplete_count": validation["incomplete_count"],
            "governance_visibility_count": validation["governance_visibility_count"],
            "integrity_visibility_count": validation["integrity_visibility_count"],
            "uncertainty_visibility_count": validation["uncertainty_visibility_count"],
            "missing_evidence_visibility_count": validation["missing_evidence_visibility_count"],
            "hidden_aggregation_finding_count": validation["hidden_aggregation_finding_count"],
            "hidden_visibility_count": validation["hidden_visibility_count"],
            "execution_boundary_violation_count": validation["execution_boundary_violation_count"],
            "recommendation_ranking_scoring_selection_violation_count": validation[
                "recommendation_ranking_scoring_selection_violation_count"
            ],
        },
        "deterministic_guarantees": {
            "aggregation_serialization_stable": serialization["stable"],
            "aggregation_hash_stable": hashing["stable"],
            "aggregation_hash": hash_transition_aggregation_report(aggregation_report),
            "aggregation_summary_hash": aggregation_report.summary.deterministic_summary_hash,
            "serialization_first_length": serialization["first_length"],
            "serialization_second_length": serialization["second_length"],
            "hash_algorithm": hashing["hash_algorithm"],
        },
        "deterministic_guarantee_summary": {
            "outputs_are_deterministic": serialization["stable"] and hashing["stable"],
            "finding_order_is_stable": True,
            "visibility_order_is_stable": True,
            "serialization_is_stable": serialization["stable"],
            "hashing_is_stable": hashing["stable"],
            "repeated_equivalent_aggregation_inputs_produce_equivalent_outputs": True,
        },
        "replay_guarantees": {
            "replay_safe_aggregation_finding_count": validation["replay_safe_aggregation_finding_count"],
            "replay_continuity_preserved_count": validation["replay_continuity_preserved_count"],
            "all_findings_have_replay_evidence": validation["replay_safe_aggregation_finding_count"]
            == validation["aggregation_finding_count"],
        },
        "rollback_guarantees": {
            "rollback_safe_aggregation_finding_count": validation["rollback_safe_aggregation_finding_count"],
            "rollback_continuity_preserved_count": validation["rollback_continuity_preserved_count"],
            "all_findings_have_rollback_evidence": validation["rollback_safe_aggregation_finding_count"]
            == validation["aggregation_finding_count"],
        },
        "provenance_guarantees": {
            "provenance_safe_aggregation_finding_count": validation[
                "provenance_safe_aggregation_finding_count"
            ],
            "provenance_continuity_preserved_count": validation["provenance_continuity_preserved_count"],
            "all_findings_preserve_provenance": validation["provenance_safe_aggregation_finding_count"]
            == validation["aggregation_finding_count"],
        },
        "explainability_guarantees": {
            "explainability_safe_aggregation_finding_count": validation[
                "explainability_safe_aggregation_finding_count"
            ],
            "explainability_continuity_preserved_count": validation[
                "explainability_continuity_preserved_count"
            ],
            "all_findings_have_explainability": validation["finding_not_fail_visible_count"] == 0,
            "all_visibility_is_fail_visible": validation["visibility_not_fail_visible_count"] == 0,
            "hidden_aggregation_finding_count": validation["hidden_aggregation_finding_count"],
            "hidden_visibility_count": validation["hidden_visibility_count"],
        },
        "non_execution_guarantees": {
            "orchestration_execution_absent": not aggregation_report.orchestration_execution_enabled,
            "transition_execution_absent": not aggregation_report.transition_execution_enabled,
            "graph_traversal_absent": not aggregation_report.graph_traversal_enabled,
            "routing_absent": not aggregation_report.routing_enabled,
            "scheduling_absent": not aggregation_report.scheduling_enabled,
            "dispatch_absent": not aggregation_report.dispatch_enabled,
            "runtime_orchestration_engine_absent": not aggregation_report.runtime_orchestration_engine_enabled,
            "runtime_mutation_absent": not aggregation_report.runtime_mutation_enabled,
            "authorization_absent": not aggregation_report.authorization_enabled,
            "approval_absent": not aggregation_report.approval_enabled,
            "optimization_absent": not aggregation_report.optimization_enabled,
            "recommendation_absent": not aggregation_report.recommendation_enabled,
            "ranking_absent": not aggregation_report.ranking_enabled,
            "scoring_absent": not aggregation_report.scoring_enabled,
            "selection_absent": not aggregation_report.selection_enabled,
            "prioritization_absent": not aggregation_report.prioritization_enabled,
            "weighting_absent": not aggregation_report.weighting_enabled,
            "autonomous_behavior_absent": not aggregation_report.autonomous_behavior_enabled,
            "callable_orchestration_flow_absent": not aggregation_report.callable_orchestration_flow_enabled,
            "transition_handler_absent": not aggregation_report.transition_handler_enabled,
            "runtime_state_machine_absent": not aggregation_report.runtime_state_machine_enabled,
            "production_behavior_absent": not aggregation_report.production_behavior_enabled,
            "hidden_fallback_absent": not aggregation_report.hidden_fallback_enabled,
            "silent_correction_absent": not aggregation_report.silent_correction_enabled,
            "report_execution_capability_violation_count": validation[
                "report_execution_capability_violation_count"
            ],
        },
        "descriptive_aggregation_guarantees": {
            "visibility_is_descriptive_only": validation["visibility_not_fail_visible_count"] == 0,
            "risk_visibility_is_descriptive_only": validation["risk_visibility_selection_violation_count"] == 0,
            "no_prioritization": not aggregation_report.prioritization_enabled,
            "no_weighting": not aggregation_report.weighting_enabled,
            "no_recommendation_behavior": not aggregation_report.recommendation_enabled,
            "no_ranking_behavior": not aggregation_report.ranking_enabled,
            "no_scoring_behavior": not aggregation_report.scoring_enabled,
            "no_selection_behavior": not aggregation_report.selection_enabled,
            "non_selective_confirmation": validation["non_selective_confirmation"],
        },
        "classification_semantics": {
            AGGREGATION_CLASSIFICATION_AGGREGATED: "all required transition intelligence domains and deterministic evidence are present",
            AGGREGATION_CLASSIFICATION_PARTIALLY_AGGREGATED: "some required domains exist while aggregation guarantees remain visibly incomplete",
            AGGREGATION_CLASSIFICATION_UNAGGREGATED: "aggregation cannot be safely constructed under current deterministic coverage",
            AGGREGATION_CLASSIFICATION_BLOCKED: "governance, integrity, or execution-boundary preservation blocks aggregation",
            AGGREGATION_CLASSIFICATION_UNSUPPORTED: "aggregation domain or evidence is outside supported deterministic scope",
            AGGREGATION_CLASSIFICATION_PROHIBITED: "requested aggregation behavior violates non-execution or non-selection boundaries",
            AGGREGATION_CLASSIFICATION_UNKNOWN: "aggregation semantics, provenance meaning, continuity meaning, or evidence meaning is uncertain",
            AGGREGATION_CLASSIFICATION_INCOMPLETE: "required domains, evidence, provenance, continuity, or explainability are missing",
        },
        "finding_semantics": {
            AGGREGATION_FINDING_FOUNDATION: "foundation evidence aggregation finding",
            AGGREGATION_FINDING_BOUNDARY: "boundary evidence aggregation finding",
            AGGREGATION_FINDING_COMPATIBILITY: "compatibility evidence aggregation finding",
            AGGREGATION_FINDING_EVALUATION: "evaluation evidence aggregation finding",
            AGGREGATION_FINDING_SESSION: "session evidence aggregation finding",
            AGGREGATION_FINDING_SCENARIO: "scenario evidence aggregation finding",
            AGGREGATION_FINDING_VISIBILITY: "visibility aggregation finding",
            AGGREGATION_FINDING_CONTINUITY: "continuity aggregation finding",
            AGGREGATION_FINDING_PROVENANCE: "provenance aggregation finding",
            AGGREGATION_FINDING_EXPLAINABILITY: "explainability aggregation finding",
            AGGREGATION_FINDING_GOVERNANCE: "governance aggregation finding",
            AGGREGATION_FINDING_INTEGRITY: "integrity aggregation finding",
            AGGREGATION_FINDING_UNSUPPORTED: "unsupported aggregation finding",
            AGGREGATION_FINDING_PROHIBITED: "prohibited aggregation behavior finding",
            AGGREGATION_FINDING_MISSING_EVIDENCE: "missing aggregation evidence finding",
            AGGREGATION_FINDING_UNCERTAINTY: "uncertain aggregation evidence finding",
        },
        "visibility_semantics": {
            AGGREGATION_VISIBILITY_FAIL_VISIBLE: "fail-visible finding aggregation",
            AGGREGATION_VISIBILITY_UNSUPPORTED_STATE: "unsupported-state visibility aggregation",
            AGGREGATION_VISIBILITY_PROHIBITED_STATE: "prohibited-state visibility aggregation",
            AGGREGATION_VISIBILITY_UNCERTAINTY: "uncertainty visibility aggregation",
            AGGREGATION_VISIBILITY_CONTINUITY: "continuity visibility aggregation",
            AGGREGATION_VISIBILITY_PROVENANCE: "provenance visibility aggregation",
            AGGREGATION_VISIBILITY_EXPLAINABILITY: "explainability visibility aggregation",
            AGGREGATION_VISIBILITY_INTEGRITY: "integrity visibility aggregation",
            AGGREGATION_VISIBILITY_GOVERNANCE: "governance visibility aggregation",
            AGGREGATION_VISIBILITY_SCENARIO_RISK: "scenario risk visibility aggregation",
            AGGREGATION_VISIBILITY_MISSING_EVIDENCE: "missing-evidence visibility aggregation",
        },
        "aggregation_report": export_transition_aggregation_report(aggregation_report),
        "explicit_limitations": [
            "v3.9 Phase 7 transition intelligence aggregation is non-executable",
            "v3.9 Phase 7 does not enable orchestration execution",
            "v3.9 Phase 7 does not enable transition execution",
            "v3.9 Phase 7 does not enable graph traversal",
            "v3.9 Phase 7 does not enable routing, scheduling, or dispatch",
            "v3.9 Phase 7 does not enable runtime orchestration engines",
            "v3.9 Phase 7 does not enable runtime mutation",
            "v3.9 Phase 7 does not enable authorization or approval systems",
            "v3.9 Phase 7 does not enable optimization or recommendations",
            "v3.9 Phase 7 does not enable ranking, scoring, or selection",
            "v3.9 Phase 7 does not prioritize or weight outcomes",
            "v3.9 Phase 7 does not imply approval or preferred outcomes",
            "v3.9 Phase 7 does not enable production behavior",
        ],
        "summary": {
            "aggregation_report_status": aggregation_report.report_status,
            "validation_error_count": validation["validation_error_count"],
            "deterministic_serialization_verified": serialization["stable"],
            "deterministic_hashing_verified": hashing["stable"],
            "aggregated_count": validation["aggregated_count"],
            "partially_aggregated_count": validation["partially_aggregated_count"],
            "unaggregated_count": validation["unaggregated_count"],
            "blocked_count": validation["blocked_count"],
            "unsupported_count": validation["unsupported_count"],
            "prohibited_count": validation["prohibited_count"],
            "unknown_count": validation["unknown_count"],
            "incomplete_count": validation["incomplete_count"],
            "aggregation_finding_count": validation["aggregation_finding_count"],
            "aggregation_visibility_count": validation["aggregation_visibility_count"],
            "governance_visibility_count": validation["governance_visibility_count"],
            "integrity_visibility_count": validation["integrity_visibility_count"],
            "uncertainty_visibility_count": validation["uncertainty_visibility_count"],
            "missing_evidence_visibility_count": validation["missing_evidence_visibility_count"],
            "hidden_aggregation_finding_count": validation["hidden_aggregation_finding_count"],
            "hidden_visibility_count": validation["hidden_visibility_count"],
            "execution_boundary_violation_count": validation["execution_boundary_violation_count"],
            "recommendation_ranking_scoring_selection_violation_count": validation[
                "recommendation_ranking_scoring_selection_violation_count"
            ],
            "report_execution_capability_violation_count": validation[
                "report_execution_capability_violation_count"
            ],
            "replay_verified": validation["replay_safe_aggregation_finding_count"]
            == validation["aggregation_finding_count"],
            "rollback_verified": validation["rollback_safe_aggregation_finding_count"]
            == validation["aggregation_finding_count"],
            "provenance_verified": validation["provenance_safe_aggregation_finding_count"]
            == validation["aggregation_finding_count"],
            "explainability_verified": validation["finding_not_fail_visible_count"] == 0,
            "visibility_verified": validation["visibility_not_fail_visible_count"] == 0,
            "non_executable_verified": aggregation_report.non_executable,
            "orchestration_boundaries_enforced": validation["report_execution_capability_violation_count"] == 0,
            "descriptive_aggregation_verified": validation["non_selective_confirmation"],
            "source_artifact_continuity_preserved": present_source_artifact_count == source_artifact_count,
        },
    }
    report["deterministic_report_hash"] = deterministic_hash(
        {key: value for key, value in report.items() if key != "deterministic_report_hash"}
    )
    return report


def write_transition_aggregation_markdown_report(report: dict[str, Any], output_path: Path) -> None:
    lines = [
        "# v3.9 Transition Intelligence Aggregation",
        "",
        "## What Phase 7 Adds",
        "",
        "v3.9 Phase 7 aggregates all prior deterministic transition evidence into unified descriptive transition intelligence summaries.",
        "",
        "It aggregates findings, evidence, visibility, continuity, provenance, scenario risk visibility, and deterministic classifications without enabling execution behavior.",
        "",
        "This phase does NOT enable orchestration execution, traversal, routing, scheduling, dispatch, optimization, recommendation, ranking, scoring, selection, authorization, approval, or runtime mutation.",
        "",
        "## Aggregation Is Not Orchestration",
        "",
        "Aggregation combines evidence records into deterministic summaries. It does not execute transitions, authorize transitions, traverse graphs, choose routes, schedule dispatch, approve behavior, mutate runtime state, or produce production pathways.",
        "",
        "## Deterministic Evidence Aggregation",
        "",
        "Phase 7 aggregates the v3.9 foundation, boundary, compatibility, evaluation, session, and scenario evidence domains while preserving deterministic ordering and stable hashes.",
        "",
        "## Visibility Aggregation",
        "",
        "Visibility aggregation is descriptive only. It records fail-visible findings, unsupported states, prohibited states, uncertainty, continuity, provenance, explainability, integrity, governance, and scenario risk visibility.",
        "",
        "## Fail-Visible Findings",
        "",
        "Every aggregation finding includes a reason, evidence reference, provenance reference, continuity reference, and explainability message.",
        "",
        "No aggregation state or visibility record is hidden, silently corrected, prioritized, weighted, recommended, ranked, scored, or selected.",
        "",
        "## Builds On Previous v3.9 Layers",
        "",
        "Phase 7 builds on transition foundations, boundary intelligence, compatibility intelligence, evaluation intelligence, session intelligence, and scenario intelligence without changing their reasoning.",
        "",
        "## Aggregation Totals",
        "",
        f"- Aggregated: `{report['summary']['aggregated_count']}`",
        f"- Partially aggregated: `{report['summary']['partially_aggregated_count']}`",
        f"- Unaggregated: `{report['summary']['unaggregated_count']}`",
        f"- Blocked: `{report['summary']['blocked_count']}`",
        f"- Unsupported: `{report['summary']['unsupported_count']}`",
        f"- Prohibited: `{report['summary']['prohibited_count']}`",
        f"- Unknown: `{report['summary']['unknown_count']}`",
        f"- Incomplete: `{report['summary']['incomplete_count']}`",
        "",
        "## Visibility Totals",
        "",
        f"- Aggregation findings: `{report['summary']['aggregation_finding_count']}`",
        f"- Aggregation visibility records: `{report['summary']['aggregation_visibility_count']}`",
        f"- Governance visibility: `{report['summary']['governance_visibility_count']}`",
        f"- Integrity visibility: `{report['summary']['integrity_visibility_count']}`",
        f"- Uncertainty visibility: `{report['summary']['uncertainty_visibility_count']}`",
        f"- Missing-evidence visibility: `{report['summary']['missing_evidence_visibility_count']}`",
        f"- Hidden aggregation findings: `{report['summary']['hidden_aggregation_finding_count']}`",
        f"- Hidden visibility records: `{report['summary']['hidden_visibility_count']}`",
        f"- Execution-boundary violation detections: `{report['summary']['execution_boundary_violation_count']}`",
        f"- Recommendation/ranking/scoring/selection violation detections: `{report['summary']['recommendation_ranking_scoring_selection_violation_count']}`",
        "",
        "## Deterministic Guarantees",
        "",
        f"- Aggregation report status: `{report['summary']['aggregation_report_status']}`",
        f"- Validation errors: `{report['summary']['validation_error_count']}`",
        f"- Serialization stable: `{report['summary']['deterministic_serialization_verified']}`",
        f"- Hash stable: `{report['summary']['deterministic_hashing_verified']}`",
        f"- Aggregation hash: `{report['deterministic_guarantees']['aggregation_hash']}`",
        f"- Aggregation summary hash: `{report['deterministic_guarantees']['aggregation_summary_hash']}`",
        f"- Report hash: `{report['deterministic_report_hash']}`",
        "",
        "## Replay Rollback Provenance And Explainability",
        "",
        f"- Replay verified: `{report['summary']['replay_verified']}`",
        f"- Rollback verified: `{report['summary']['rollback_verified']}`",
        f"- Provenance verified: `{report['summary']['provenance_verified']}`",
        f"- Explainability verified: `{report['summary']['explainability_verified']}`",
        f"- Visibility verified: `{report['summary']['visibility_verified']}`",
        f"- Descriptive aggregation verified: `{report['summary']['descriptive_aggregation_verified']}`",
        "",
        "## What Remains Prohibited",
        "",
        "- Orchestration execution.",
        "- Transition execution.",
        "- Graph traversal.",
        "- Routing.",
        "- Scheduling.",
        "- Dispatch.",
        "- Runtime orchestration engines.",
        "- Runtime mutation.",
        "- Authorization systems.",
        "- Approval systems.",
        "- Optimization.",
        "- Recommendations.",
        "- Ranking.",
        "- Scoring.",
        "- Selection.",
        "- Prioritization.",
        "- Weighting.",
        "- Autonomous behavior.",
        "- Callable orchestration flows.",
        "- Transition handlers.",
        "- Runtime state machines.",
        "- Production behavior.",
        "",
        "## Generated Evidence",
        "",
        "- JSON report: `docs/generated/v3_9_transition_intelligence_aggregation_report.json`",
        "- This migration note: `docs/migration/V3_9_TRANSITION_INTELLIGENCE_AGGREGATION.md`",
    ]
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _source_artifact_status(repo_root: Path, relative_path: str) -> dict[str, Any]:
    artifact_path = repo_root / relative_path
    if not artifact_path.exists():
        return {
            "path": relative_path,
            "present": False,
            "artifact_hash": "",
        }
    text = artifact_path.read_text(encoding="utf-8")
    try:
        payload: Any = json.loads(text)
    except json.JSONDecodeError:
        payload = {"raw_text": text}
    return {
        "path": relative_path,
        "present": True,
        "artifact_hash": deterministic_hash(payload),
    }
