"""Item type identifier slugs — canonical across the codebase."""

ITEM_TYPE_IDS: list[str] = [
    "amulet",
    "axe",
    "belt",
    "boots",
    "bow",
    "catalyst",
    "chest",
    "crossbow",
    "dagger",
    "fist",
    "gloves",
    "helm",
    "idol_1x1",
    "idol_1x2",
    "idol_1x3",
    "idol_1x4",
    "idol_2x1",
    "idol_2x2",
    "idol_3x1",
    "idol_4x1",
    "mace",
    "polearm",
    "quiver",
    "relic",
    "ring",
    "sceptre",
    "shield",
    "staff",
    "sword",
    "wand",
]
