"""Add affixes_before to CraftStep for undo support

Revision ID: 21bc975a3016
Revises: 93e06c1a641f
Create Date: 2026-03-22 00:22:37.633556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bc975a3016'
down_revision = '93e06c1a641f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('craft_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affixes_before', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('craft_steps', schema=None) as batch_op:
        batch_op.drop_column('affixes_before')

    # ### end Alembic commands ###
