"""remove loot filters

Revision ID: 3ffd55fa24ac
Revises: cf57d3c33180
Create Date: 2026-03-15 04:42:33.193606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ffd55fa24ac'
down_revision = 'cf57d3c33180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_rules')
    with op.batch_alter_table('loot_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loot_filters_slug'))

    op.drop_table('loot_filters')
    with op.batch_alter_table('build_skills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('build_skills_build_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'builds', ['build_id'], ['id'])

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('votes_build_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'builds', ['build_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('votes_build_id_fkey'), 'builds', ['build_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('build_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('build_skills_build_id_fkey'), 'builds', ['build_id'], ['id'], ondelete='CASCADE')

    op.create_table('loot_filters',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('playstyle', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('strictness', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('patch_version', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('loot_filters_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('loot_filters_pkey'))
    )
    with op.batch_alter_table('loot_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loot_filters_slug'), ['slug'], unique=True)

    op.create_table('filter_rules',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('filter_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('priority', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['loot_filters.id'], name=op.f('filter_rules_filter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('filter_rules_pkey'))
    )
    # ### end Alembic commands ###
