"""initial schema

Revision ID: cf57d3c33180
Revises: 
Create Date: 2026-03-14 23:10:56.663423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf57d3c33180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affix_defs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('affix_type', sa.String(length=8), nullable=False),
    sa.Column('stat_key', sa.String(length=64), nullable=False),
    sa.Column('tier_ranges', sa.JSON(), nullable=False),
    sa.Column('applicable_types', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('base_implicit', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('passive_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_class', sa.String(length=32), nullable=False),
    sa.Column('mastery', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(length=16), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('max_points', sa.SmallInteger(), nullable=False),
    sa.Column('connections', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discord_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('discriminator', sa.String(length=8), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_discord_id'), ['discord_id'], unique=True)

    op.create_table('builds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('character_class', sa.String(length=32), nullable=False),
    sa.Column('mastery', sa.String(length=32), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('passive_tree', sa.JSON(), nullable=False),
    sa.Column('gear', sa.JSON(), nullable=False),
    sa.Column('is_ssf', sa.Boolean(), nullable=False),
    sa.Column('is_hc', sa.Boolean(), nullable=False),
    sa.Column('is_ladder_viable', sa.Boolean(), nullable=False),
    sa.Column('is_budget', sa.Boolean(), nullable=False),
    sa.Column('patch_version', sa.String(length=16), nullable=False),
    sa.Column('cycle', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builds_slug'), ['slug'], unique=True)

    op.create_table('craft_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=True),
    sa.Column('item_level', sa.SmallInteger(), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('instability', sa.SmallInteger(), nullable=False),
    sa.Column('forge_potential', sa.SmallInteger(), nullable=False),
    sa.Column('affixes', sa.JSON(), nullable=False),
    sa.Column('is_fractured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('craft_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_craft_sessions_slug'), ['slug'], unique=True)

    op.create_table('loot_filters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('playstyle', sa.String(length=32), nullable=True),
    sa.Column('strictness', sa.String(length=16), nullable=True),
    sa.Column('patch_version', sa.String(length=16), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loot_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loot_filters_slug'), ['slug'], unique=True)

    op.create_table('build_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.Column('points_allocated', sa.SmallInteger(), nullable=False),
    sa.Column('spec_tree', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'slot', name='uq_build_skill_slot')
    )
    op.create_table('craft_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.SmallInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('affix_name', sa.String(length=64), nullable=True),
    sa.Column('tier_before', sa.SmallInteger(), nullable=True),
    sa.Column('tier_after', sa.SmallInteger(), nullable=True),
    sa.Column('instability_before', sa.SmallInteger(), nullable=False),
    sa.Column('instability_after', sa.SmallInteger(), nullable=False),
    sa.Column('fracture_risk_pct', sa.Float(), nullable=False),
    sa.Column('roll', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('fp_before', sa.SmallInteger(), nullable=False),
    sa.Column('fp_after', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['craft_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filter_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['loot_filters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'build_id', name='uq_user_build_vote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('filter_rules')
    op.drop_table('craft_steps')
    op.drop_table('build_skills')
    with op.batch_alter_table('loot_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loot_filters_slug'))

    op.drop_table('loot_filters')
    with op.batch_alter_table('craft_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_craft_sessions_slug'))

    op.drop_table('craft_sessions')
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builds_slug'))

    op.drop_table('builds')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_discord_id'))

    op.drop_table('users')
    op.drop_table('passive_nodes')
    op.drop_table('item_types')
    op.drop_table('affix_defs')
    # ### end Alembic commands ###
