"""widen affix_defs stat_key and class_requirement columns

Revision ID: e07407b85e20
Revises: b4c1f0f6d2aa
Create Date: 2026-03-21 23:47:45.866407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07407b85e20'
down_revision = 'b4c1f0f6d2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affix_defs', schema=None) as batch_op:
        batch_op.alter_column('stat_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('class_requirement',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affix_defs', schema=None) as batch_op:
        batch_op.alter_column('class_requirement',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('stat_key',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
