"""add FK indexes for builds.author_id, craft_sessions.user_id, craft_steps.session_id, votes.build_id

Revision ID: f8953bcaab80
Revises: a1b2c3d4e5f6
Create Date: 2026-04-04 18:28:06.799542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8953bcaab80'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builds_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('craft_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_craft_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('craft_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_craft_steps_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_build_id'), ['build_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_build_id'))

    with op.batch_alter_table('craft_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_craft_steps_session_id'))

    with op.batch_alter_table('craft_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_craft_sessions_user_id'))

    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builds_author_id'))

    # ### end Alembic commands ###
